Profile Picture added on API and Backend
nerdapplabs/authOauth pull request #6
Opened 2017-02-15 13:50 UTC by aksinha-nerdapplabs

PR for [Issue# 5](https://github.com/nerdapplabs/authOauth/issues/5)

2017-02-15 14:09 UTC, praveen-garg requested changes
minor comments;

2017-02-15 14:09 UTC, praveen-garg commented on src/ApiBundle/Controller/Admin/UserController.php
> +              $this->logMessage(400, 'danger', $e->getMessage());
should not we use logMessageAndFlash?

2017-02-15 14:09 UTC, praveen-garg commented on src/ApiBundle/Controller/Admin/UserController.php
> +              $this->logMessage(400, 'danger', $e->getMessage());
logMessageAndFlash?

2017-02-15 14:09 UTC, praveen-garg commented on src/ApiBundle/Controller/AuthController.php
> +      *      {"name"="image", "dataType"="image/jpeg, image/jpg, image/gif, image/png", "required"=false, "description"="Profile Picture within 1024k size"},
where did we limit 1024K

2017-02-15 14:09 UTC, praveen-garg commented on src/ApiBundle/Entity/User.php
> +    *     maxSize = "1024k",
Okay, here it is! cool!

2017-02-15 14:56 UTC, praveen-garg commented on src/ApiBundle/Entity/User.php
> +    *     maxSize = "1024k",
As discussed, User (who is signing up) should be able add/ remove or update user profile image; not the admin only.

2017-02-17 14:32 UTC, praveen-garg commented on src/ApiBundle/Form/UserType.php
> +            ->add('password', TextType::class)
changed it back to TextType? 
it was chnaged to PasswordType in last PR
https://github.com/nerdapplabs/authOauth/pull/9/files#diff-3683af68b1a14d46bf30b457a8ec4ddfR31

2017-02-18 10:25 UTC, aksinha-nerdapplabs commented
@praveen-garg have a look. Changes are final till now.

2017-02-18 12:54 UTC, praveen-garg commented on src/ApiBundle/Controller/AuthController.php
> +        $user->setLastname($request->request->get('lastname') ? $request->request->get('lastname') : null);
should not we make it EMPTY string ? ""

2017-02-18 12:56 UTC, praveen-garg commented on src/ApiBundle/Controller/AuthController.php
> +        $loginConfirmation = $this->container->getParameter('login_confirmation');
what is the use of this var?

2017-02-18 12:56 UTC, praveen-garg commented on src/ApiBundle/Controller/AuthController.php
> +        if (true == $this->container->getParameter('email_confirmation') ) {
email_confirmation > registration_requires_email_confirmation

2017-02-18 12:57 UTC, praveen-garg commented on src/ApiBundle/Controller/AuthController.php
> +            return new Response();
can you please explain more? 

If no image file, then return empty response ?

2017-02-18 12:59 UTC, praveen-garg commented on src/ApiBundle/Controller/AuthController.php
> +      *      {"name"="image", "dataType"="image/jpeg, image/jpg, image/gif, image/png", "required"=false, "description"="jpeg/jpg/png/gif Pic Size: 1024k, Width: 50-300px, Height: 50-300px"},
older looks better!

2017-02-18 13:00 UTC, praveen-garg commented on src/ApiBundle/Resources/config/config.yml
> +    login_confirmation: false
see previous comments

2017-02-18 15:01 UTC, praveen-garg commented
@aksinha-nerdapplabs  we must keep PR specific to the issue; not sure why this PR has  registration_requires_email_confirmation related change. a new PR (with minimum & to the point chnages) could have been easy to review/ test and merge

2017-02-18 16:14 UTC, aksinha-nerdapplabs commented on src/ApiBundle/Controller/AuthController.php
> +            return new Response();
yeah, Empty with 200 ok.

2017-02-20 10:14 UTC, praveen-garg commented on src/ApiBundle/Controller/AuthController.php
> +        $loginConfirmation = $this->container->getParameter('login_confirmation');
login_confirmation > login_required_after_signup

2017-02-21 06:23 UTC, praveen-garg commented on src/ApiBundle/Controller/UserController.php
> +            // We simply do not authenticate users which do not pass the user
but we should log?

2017-02-21 09:44 UTC, praveen-garg commented on src/ApiBundle/Controller/Admin/UserController.php
> +                                  'ROLE_ADMIN' => 'ROLE_ADMIN',
? yes?

2017-02-21 09:44 UTC, praveen-garg commented on src/ApiBundle/Controller/Admin/UserController.php
> +                                  'ROLE_ADMIN' => 'ROLE_ADMIN',
are your sure?

2017-02-22 14:32 UTC, praveen-garg approved these changes
DRY review; need more testing..

2017-02-22 14:32 UTC, merged